"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const channel_repository_1 = require("../../repositories/channel.repository");
const jwt_service_1 = __importDefault(require("../utils/jwt.service"));
const auth_middleware_1 = __importDefault(require("../middlewares/auth.middleware"));
const channel_usecase_1 = require("../../usecase/channel.usecase");
const role_repository_1 = require("../../repositories/role.repository");
const community_repository_1 = require("../../repositories/community.repository");
const RBACService_1 = require("../utils/RBACService");
const channel_controller_1 = __importDefault(require("../../controller/channel.controller"));
const chat_repository_1 = require("../../repositories/chat.repository");
const channelRouter = (0, express_1.Router)();
const channelRepository = new channel_repository_1.ChannelRepository;
const roleRepository = new role_repository_1.RoleRepository;
const communityRepository = new community_repository_1.CommunityRepository();
const chatRepository = new chat_repository_1.ChatRepository();
const jwtService = new jwt_service_1.default();
const authMiddleware = new auth_middleware_1.default(jwtService);
const rbacService = new RBACService_1.RBACService(roleRepository, communityRepository);
const channelUsecase = new channel_usecase_1.ChannelUseCase(channelRepository, roleRepository, rbacService, chatRepository);
const channelController = new channel_controller_1.default(channelUsecase);
channelRouter.use(authMiddleware.isAuthenticated.bind(authMiddleware));
channelRouter.route("/create/:communityId").post(channelController.createChannel.bind(channelController));
channelRouter.route("/:id").get(channelController.getChannelById.bind(channelController));
channelRouter.route("/list/:communityId").get(channelController.getAccessibleChannels.bind(channelController));
channelRouter.route("/search/:communityId").get(channelController.searchAccessibleChannels.bind(channelController));
channelRouter.route("/update/:communityId/:channelId").put(channelController.updateChannel.bind(channelController));
channelRouter.route("/delete/:communityId/:channelId").delete(channelController.deleteChannel.bind(channelController));
exports.default = channelRouter;
