"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const multer_1 = __importDefault(require("multer"));
const jwt_service_1 = __importDefault(require("../utils/jwt.service"));
const auth_middleware_1 = __importDefault(require("../middlewares/auth.middleware"));
const chat_controller_1 = require("../../controller/chat.controller");
const chatDependencies_1 = require("../chatDependencies");
const chatRouter = (0, express_1.Router)();
const jwtService = new jwt_service_1.default();
const authMiddleware = new auth_middleware_1.default(jwtService);
const chatUseCase = (0, chatDependencies_1.createChatUseCase)();
const chatController = new chat_controller_1.ChatController(chatUseCase);
const MB = 1024 * 1024;
const imageUpload = (0, multer_1.default)({ storage: multer_1.default.memoryStorage(), limits: { fileSize: 5 * MB } });
const videoUpload = (0, multer_1.default)({ storage: multer_1.default.memoryStorage(), limits: { fileSize: 50 * MB } });
const audioUpload = (0, multer_1.default)({ storage: multer_1.default.memoryStorage(), limits: { fileSize: 10 * MB } });
const fileUpload = (0, multer_1.default)({ storage: multer_1.default.memoryStorage(), limits: { fileSize: 25 * MB } });
chatRouter.use(authMiddleware.isAuthenticated.bind(authMiddleware));
chatRouter.get("/messages/:chatId", chatController.getMessageHistory.bind(chatController));
chatRouter.get("/gifs", chatController.getGifs.bind(chatController));
chatRouter.get("/stickers", chatController.getStickers.bind(chatController));
chatRouter.get("/link-preview", chatController.getLinkPreview.bind(chatController));
chatRouter.post("/messages/image", imageUpload.single("file"), chatController.sendImageMessage.bind(chatController));
chatRouter.post("/messages/video", videoUpload.single("file"), chatController.sendVideoMessage.bind(chatController));
chatRouter.post("/messages/audio", audioUpload.single("file"), chatController.sendAudioMessage.bind(chatController));
chatRouter.post("/messages/file", fileUpload.single("file"), chatController.sendFileMessage.bind(chatController));
chatRouter.patch("/messages/:messageId", chatController.patchMessage.bind(chatController));
chatRouter.delete("/messages/:messageId", chatController.deleteMessage.bind(chatController));
chatRouter.post("/messages/:messageId/reactions", chatController.setReaction.bind(chatController));
chatRouter.delete("/messages/:messageId/reactions", chatController.removeReaction.bind(chatController));
chatRouter.post("/messages/:messageId/vote", chatController.votePoll.bind(chatController));
exports.default = chatRouter;
