"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const friends_controller_1 = __importDefault(require("../../controller/friends.controller"));
const friends_repository_1 = __importDefault(require("../../repositories/friends.repository"));
const friends_usecase_1 = __importDefault(require("../../usecase/friends.usecase"));
const jwt_service_1 = __importDefault(require("../utils/jwt.service"));
const auth_middleware_1 = __importDefault(require("../middlewares/auth.middleware"));
const friendRouter = (0, express_1.Router)();
const jwtService = new jwt_service_1.default();
const authMiddleware = new auth_middleware_1.default(jwtService);
const friendRepository = new friends_repository_1.default();
const friendUseCase = new friends_usecase_1.default(friendRepository);
const friendController = new friends_controller_1.default(friendUseCase);
// Apply authMiddleware to all routes
friendRouter.use(authMiddleware.isAuthenticated.bind(authMiddleware));
friendRouter.get("/search", friendController.searchUsers.bind(friendController));
friendRouter.post("/request", friendController.sendFriendRequest.bind(friendController));
friendRouter.post("/accept_request", friendController.acceptFriendRequest.bind(friendController));
friendRouter.post("/reject_request", friendController.rejectFriendRequest.bind(friendController));
friendRouter.delete("/remove_friend/:friendId", friendController.removeFriend.bind(friendController));
friendRouter.get("/pending_requests", friendController.getPendingFriendRequests.bind(friendController));
friendRouter.get("/online", friendController.getOnlineFriends.bind(friendController));
friendRouter.get("/all", friendController.getAllFriends.bind(friendController));
friendRouter.post("/block_user", friendController.blockUser.bind(friendController));
friendRouter.post("/unblock_user", friendController.unblockUser.bind(friendController));
friendRouter.get("/blocked", friendController.getAllBlockedUsers.bind(friendController));
exports.default = friendRouter;
