"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const role_repository_1 = require("../../repositories/role.repository");
const community_repository_1 = require("../../repositories/community.repository");
const RBACService_1 = require("../utils/RBACService");
const auth_middleware_1 = __importDefault(require("../middlewares/auth.middleware"));
const jwt_service_1 = __importDefault(require("../utils/jwt.service"));
const role_usecase_1 = require("../../usecase/role.usecase");
const role_controller_1 = __importDefault(require("../../controller/role.controller"));
const roleRouter = (0, express_1.Router)();
const roleRepository = new role_repository_1.RoleRepository();
const communityRepository = new community_repository_1.CommunityRepository();
const jwtService = new jwt_service_1.default();
const authMiddleware = new auth_middleware_1.default(jwtService);
const rbacService = new RBACService_1.RBACService(roleRepository, communityRepository);
const roleUsecase = new role_usecase_1.RoleUseCase(roleRepository, rbacService);
const roleController = new role_controller_1.default(roleUsecase);
roleRouter.use(authMiddleware.isAuthenticated.bind(authMiddleware));
roleRouter.route("/create/:communityId").post(roleController.createRole.bind(roleController));
roleRouter.route("/:id").get(roleController.getRoleById.bind(roleController));
roleRouter.route("/user/:communityId").get(roleController.getUserRoles.bind(roleController));
roleRouter.route("/update/:communityId/:roleId").put(roleController.updateRole.bind(roleController));
roleRouter.route("/delete/:communityId/:roleId").delete(roleController.deleteRole.bind(roleController));
roleRouter.route("/list/:communityId").get(roleController.listRoles.bind(roleController));
exports.default = roleRouter;
