"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const jwt_service_1 = __importDefault(require("../utils/jwt.service"));
const auth_middleware_1 = __importDefault(require("../middlewares/auth.middleware"));
const channel_repository_1 = require("../../repositories/channel.repository");
const community_repository_1 = require("../../repositories/community.repository");
const voiceroom_usecase_1 = require("../../usecase/voiceroom.usecase");
const voiceroom_controller_1 = require("../../controller/voiceroom.controller");
const voiceroomRouter = (0, express_1.Router)();
const jwtService = new jwt_service_1.default();
const authMiddleware = new auth_middleware_1.default(jwtService);
const voiceroomUseCase = new voiceroom_usecase_1.VoiceroomUseCase(new channel_repository_1.ChannelRepository(), new community_repository_1.CommunityRepository());
const voiceroomController = new voiceroom_controller_1.VoiceroomController(voiceroomUseCase);
voiceroomRouter.use(authMiddleware.isAuthenticated.bind(authMiddleware));
voiceroomRouter.get("/:channelId/presence", voiceroomController.getPresence.bind(voiceroomController));
voiceroomRouter.post("/:channelId/token", voiceroomController.getToken.bind(voiceroomController));
exports.default = voiceroomRouter;
